import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu";
import AnimationProvider from "@/components/AnimationProvider";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="" id="root">
			<body className={`${inter.className} antialiased px-8 py-4`}>
				<Menu key="menu" />
				{children}
			</body>
		</html>
	);
}
